export const environment = {
  production: true,
  API_URL: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZTAwNjE0M2MyZjgwMDAwMGFhNWUyZDg2ZjVlMjFkMCIsInN1YiI6IjY0ZjhiMDQzZTBjYTdmMDBjYmU3OTY1MCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.3kQlVzWEC13sppXAgOhZl0TNObcUMa3LCwOecg0lRh4",
};